# The part of pyrage gpuc uses: its wheel ships no stubs.
from collections.abc import Sequence

from . import x25519 as x25519

class RecipientError(Exception): ...
class EncryptError(Exception): ...
class DecryptError(Exception): ...
class IdentityError(Exception): ...

def encrypt(
    plaintext: bytes, recipients: Sequence[x25519.Recipient], armored: bool = ...
) -> bytes: ...
def decrypt(ciphertext: bytes, identities: Sequence[x25519.Identity]) -> bytes: ...
